### ISSUE TITLE
Subwoofer level always reported as 0

### ISSUE THREAD

**Issue by jakeycrx** [samuelspagl/ha_samsung_soundbar#34]
Hi,

Thank you for this integration, it really is great!  Just one very minor issue on the HW-Q90R, the subwoofer level is always reported as 0.  The subwoofer level does stay at the level I set it to, but shortly after setting the level, it goes back to being reported as 0.

![image](https://github.com/samuelspagl/ha_samsung_soundbar/assets/47118674/0727b0ba-42f0-4b06-8c02-afaa7f24a485)

The HW-Q90R subwoofer goes down to -12dB, so I had to change the native min value in number.py from -10 to -12.

**Comment by jakeycrx** [comment]
I'm on version 0.3.0.  Is it worth trying the beta?

**Comment by samuelspagl** [comment]
Like mentioned in the README, it's recommended to use the beta currently. 

You you can read through the issue mentioned there, to get a full overview over the problem. 😁
The disadvantage of the version `0.3.0` is that you will need to disable most of the custom entities. This is due to the problem that, like mentioned, its not possible currently to retrieve the status. It is still possible to control everything though. Therefore I created service calls for every aspect of the soundbar. ✌️

I will merge the beta hopefully today. :)

**Comment by jakeycrx** [comment]
Apologies, I'm not very experienced using GitHub.

How would I go about upgrading to the beta?

**Comment by samuelspagl** [comment]
Don't worry 😁

Here you'll find a link that explains everything :) 

https://hacs.xyz/docs/faq/select_version/
